name: Ubuntu Linux

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: OpenStarbound Linux x86_64
    runs-on: ubuntu-20.04

    steps:
      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libsamplerate0-dev libsdl2-dev

      - name: Install CMake & Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.29.2

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ github.job }}-${{ runner.os }}
          max-size: 250M

      - name: vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgJsonGlob: '**/source/vcpkg.json'
          vcpkgConfigurationJsonGlob: '**/source/vcpkg-configuration.json'

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/source/CMakeLists.txt'
          configurePreset: 'linux-release'
          buildPreset: 'linux-release'
          testPreset: 'linux-release'

      - name: Assemble Files
        working-directory: ${{ github.workspace }}
        run: scripts/ci/linux/assemble.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenStarbound-Linux
          path: dist.tar

      - name: Upload Client Files
        uses: actions/upload-artifact@v4
        with:
          name: OpenStarbound-Linux-Client
          path: client.tar

      - name: Upload Server Files
        uses: actions/upload-artifact@v4
        with:
          name: OpenStarbound-Linux-Server
          path: server.tar