name: Ubuntu Linux

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: OpenStarbound Linux x86_64
    runs-on: ubuntu-latest

    steps:
      - name: Install Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config ninja-build \
              libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libsdl2-dev

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: sccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          variant: sccache
          key: ${{ github.job }}-${{ runner.os }}
          max-size: 2500M

      - name: vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgJsonGlob: '**/source/vcpkg.json'
          vcpkgConfigurationJsonGlob: '**/source/vcpkg-configuration.json'

      - name: Run CMake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/source/CMakeLists.txt'
          configurePreset: 'linux-release'
          buildPreset: 'linux-release'
          testPreset: 'linux-release'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenStarbound-Dev-Linux-x86_64
          path: dist/*
